# Generated by Django 3.1.5 on 2021-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('number', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('time', models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00')], max_length=15)),
                ('doctor_name', models.CharField(default='', max_length=100)),
                ('hospital_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
