# Generated by Django 3.1.5 on 2021-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='', max_length=100)),
                ('hospital_name', models.CharField(default='', max_length=100)),
                ('patient_name', models.CharField(default='', max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('appointment_date', models.DateField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medicine', models.TextField()),
                ('days', models.IntegerField()),
                ('interval', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('B-L', 'Breakfast-Lunch'), ('L-D', 'Lunch-Dinner'), ('B-D', 'Breakfast-Dinner'), ('B-L-D', 'Breakfast-Lunch-Dinner')], max_length=10)),
                ('recommendation', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
